language: python
cache: pip
python:
  - "3.6"
# command to install dependencies
before_install:
  - wget https://sourceforge.net/projects/bbmap/files/BBMap_38.00.tar.gz -O /tmp/BBMap_37.00.tar.gz
  - tar -xvf /tmp/BBMap_37.00.tar.gz
  - export PATH=$PATH:$PWD/bbmap
  - wget https://github.com/torognes/vsearch/releases/download/v2.8.0/vsearch-2.8.0-linux-x86_64.tar.gz -O /tmp/vsearch-2.8.0-linux-x86_64.tar.gz
  - tar -xvf /tmp/vsearch-2.8.0-linux-x86_64.tar.gz
  - export PATH=$PATH:$PWD/vsearch-2.8.0-linux-x86_64/bin
  - wget http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz -O /tmp/hmmer-3.1b2-linux-intel-x86_64.tar.gz
  - tar -xvf /tmp/hmmer-3.1b2-linux-intel-x86_64.tar.gz
  - ls -la
  - export PATH=$PATH:$PWD/hmmer-3.1.b2-linux-intel-x86_64/binaries

install:
  - pip install codecov
  - pip install -e .
# command to run tests
script:
  - nosetests --with-coverage # or py.test for Python versions 3.5 and below

after_success:
  - codecov

notifications:
  email:
    - adam.rivers@ars.usda.gov
